# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# To use, run:
# pip install pre-commit-hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
      - id: check-case-conflict
  - repo: https://github.com/akaihola/darker
    rev: v2.1.1
    hooks:
      - id: darker
